name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies for back-end
        working-directory: ./backend
        run: npm ci
      
      - name: Install Dependencies for front-end
        working-directory: ./frontend
        run: npm ci

      - name: Run Tests for back-end
        working-directory: ./backend
        run: npm test

      - name: Run Tests for front-end
        working-directory: ./frontend
        run: npm test

      - name: Save Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
